### ISSUE TITLE
Twotech possibily displaying incorrect data

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/twotech#23]
At one point there was a bug in the contents of Data7, relating to seeds and seed bowls.
An artifact of this remains visible on Twotech where you can still see Twotech showing the ability to put any type of seed into a bowl of gooseberry's, when this is not actually possible.

Need to investigate if Twotech is in fact misrepresenting the data and as to why. Is it possible this data hasn't been regenerated because there is no detected change (doubtful)? Larger bug in data generation causing a lot of things not to be regenerated after an update (likely)? Bug in processing scripts, causing the output of incorrect Data7 data (not so likely)?

I have tested this is not caused by browser cache.

https://twotech.twohoursonelife.com/2743-Bowl-of-Gooseberry-Seeds

**Comment by mtklass** [comment]
Is this still a thing? I don't see all the erroneous transitions listed when I look at Bowl of Gooseberry Seeds or Bowl of Gooseberries

**Comment by connorhsm** [comment]
Appears to be resolved, thanks!
