### ISSUE TITLE
Vue3/Typescript migration follow ups

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/twotech#63]
Minor issues raised during review of #61 that were not necessary to block merge.

- [ ] Redundant comments/code in `ChangeLogCommit.ts`, `GameData.ts`, `GameObject.ts`, `BiomeInspector.vue`
- [ ] Text silhouette/shadow in search bar when viewing individual object page
- [ ] Biome filter, selected biome missing white border
- [ ] Recipe for letters broken, `../letters` route and link to it
- [ ] Timer in `MainProcessor.ts`

@mtklass I'll leave this with you, happy to pickup otherwise.

**Comment by connorhsm** [comment]
I saw this behaviour in the dev server and didn't think too much of it: the initial load of the Object page has changed, and it's arguably more jarring than it was.

Watch closely for the <1s load after I click each object.

Before:
https://github.com/user-attachments/assets/cc4cd857-cec5-4d74-9cfa-5727b9dab9f1

After:
https://github.com/user-attachments/assets/3b14365c-4d14-4ced-b635-946acb9ddbd9

Any thoughts regarding this? Pointers where I can investigate or easy wins? The small "Loading object..." factors into some of this.

**Comment by mtklass** [comment]
Ah, found it. The issue was due to how the object data was loaded and what the template components were looking for.

I can get a PR up for this separately right away, or it can go in a larger PR with fixes for other issues found with my recent changes.

https://github.com/user-attachments/assets/f7ce30e3-82b1-4a87-8c68-2be3f8e23542

**Comment by mtklass** [comment]
These issues are all addressed in my latest PR: https://github.com/twohoursonelife/twotech/pull/65
