### ISSUE TITLE
Un-craftable transitions display on craftable object pages even when "Only craftable" is enabled.

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/twotech#69]
![image](https://github.com/user-attachments/assets/dc2efea0-9dcd-4be3-ba96-1c86ef3f40c3)
https://twotech.twohoursonelife.com/14673-Light-Post

"Manholes" are an uncraftable object, I would expect any transitions that involve any uncraftable object would not display when viewing another objects page while the "Only craftable" flag is enabled.

![image](https://github.com/user-attachments/assets/b13699e9-e62e-4f1f-888c-89be2962a14d)

Open to hearing how others believe this should behave.

**Comment by mtklass** [comment]
I agree, the page should probably hide those transitions when the checkbox is checked.


Btw, I'll try to get to this and https://github.com/twohoursonelife/twotech/issues/70 soon. I have a few-years-long project that is wrapping up and shipping at work this week, so it's a busy time (in the personal/family life, as well). I should be able to find some time at some point in the next week though 🤞🤞

**Comment by mtklass** [comment]
This is fixed in PR: https://github.com/twohoursonelife/twotech/pull/71
