### ISSUE TITLE
Objects missing difficulty description display

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/twotech#70]
Missing:
https://twotech.twohoursonelife.com/15677-Unassembled-Diesel-Generator
![image](https://github.com/user-attachments/assets/e21a291c-c84e-46e1-a41d-6ca3f351b802)

Not missing (expected behaviour):
https://twotech.twohoursonelife.com/15681-Alternator-and-Stack-of-Sheet-Metal-and-Pipes
![image](https://github.com/user-attachments/assets/74229e74-c61a-49c3-82fd-39e2e944ce27)

Both of these items have their `depth` value set, which is what this descriptor is sourced from.
https://github.com/twohoursonelife/twotech/blob/d15c006268b070e0f094c2e49dea7169f704b135/src/components/ObjectInspector.vue#L56-L59
https://github.com/twohoursonelife/twotech/blob/d15c006268b070e0f094c2e49dea7169f704b135/src/components/ObjectInspector.vue#L190-L204

**Comment by mtklass** [comment]
This was a math error in the calculation that determined which text in `levels` got used. It scaled from 0->9, but the length of the array is 9, so it should scale between 0->8.

It's fixed in PR: https://github.com/twohoursonelife/twotech/pull/71

**Comment by connorhsm** [comment]
Great catch!

**Comment by connorhsm** [comment]
I had a bit more of a look into this. With your change applied, it appears that only objects with a difficulty value of 1 are given the top difficulty. Right now, this is only (and correctly) the diesel generator and variations of it.

I think this is a separate question for the `calculateDifficulty` method though, but still interesting.
https://github.com/twohoursonelife/twotech/blob/576d24a2923aeddf363c84d50d334936c19159d2/process/src/DepthCalculator.ts#L69-L74

```
Range 0.0 - 0.1: 825 objects
Range 0.1 - 0.2: 821 objects
Range 0.2 - 0.3: 826 objects
Range 0.3 - 0.4: 825 objects
Range 0.4 - 0.5: 826 objects
Range 0.5 - 0.6: 825 objects
Range 0.6 - 0.7: 826 objects
Range 0.7 - 0.8: 825 objects
Range 0.8 - 0.9: 826 objects
Range 0.9 - 1.0: 825 objects
Range 1.0 and above: 4 objects
```
Only these 4 objects seems a bit odd to me, but I'm not aware of the exact intent.
